const ROLES = {
  RESOURCE_MANAGER: 'RESOURCE_MANAGER',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

const TIMESHEET_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const EXCEPTION_TYPE = {
  WEEKEND: 'WEEKEND',
  HOLIDAY: 'HOLIDAY',
  BACKDATE: 'BACKDATE',
  ALLOCATION_BREACH: 'ALLOCATION_BREACH',
};

const REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const PROJECT_STATUS = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
};

const MAX_HOURS_PER_DAY = 12;
const MAX_DAYS_PAST = 14;
const MAX_DAYS_FUTURE = 7;

module.exports = {
  ROLES,
  TIMESHEET_STATUS,
  EXCEPTION_TYPE,
  REQUEST_STATUS,
  PROJECT_STATUS,
  MAX_HOURS_PER_DAY,
  MAX_DAYS_PAST,
  MAX_DAYS_FUTURE,
};
